version: "2"

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - staticcheck
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - whyNoLint
        - hugeParam
        - unnamedResult
        - nestingReduce
        - rangeValCopy
        - ifElseChain

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
