version: "2"

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - staticcheck

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
